- name: Prepare Configure php
  copy:
    src: "{{ php_source_src_dir }}/php.ini-production"
    dest: "{{ php_conf_path }}/php.ini-dist"
    remote_src: yes

- name: Start Configure php
  lineinfile:
    dest: "{{ php_conf_path }}/php.ini-dist"
    regexp: "^;?{{ item }}.?=.+$"
    line: "{{ item }} = {{ vars['php_' + item] }}"
    state: present
  with_items:
    - expose_php
    - memory_limit
    - max_input_time
    - max_input_vars
    - realpath_cache_size
    - file_uploads
    - upload_max_filesize
    - max_file_uploads
    - post_max_size
    - date_timezone
    - allow_url_fopen
    - output_buffering
    - short_open_tag
    - disable_functions
    - error_reporting
    - display_errors
    - display_startup_errors

- name: Migrate php.ini
  copy:
    src: "{{ php_source_src_dir }}/php.ini-dist"
    dest: "{{ php_conf_path }}/php{{item}}.ini"
    remote_src: yes
  with_items:
    - ""
    - -cli