- name: Ensure the php-fpm config and default pool exists
  copy:
    src: "{{ php_fpm_conf_path }}/{{ item.src }}"
    dest: "{{ php_fpm_conf_path }}/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  with_items:
    - { src: 'php-fpm.conf.default', dest: 'php-fpm.conf' }
    - { src: 'php-fpm.d/www.conf.default', dest: 'php-fpm.d/www.conf' }
  # notify: restart php-fpm


- name: Configure php-fpm pool
  lineinfile:
    dest: "{{ php_fpm_conf_path }}/php-fpm.d/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^user.?=.+$"
      line: "user = {{ php_fpm_pool_user }}"
    - regexp: "^group.?=.+$"
      line: "group = {{ php_fpm_pool_group }}"
    - regexp: "^listen.?=.+$"
      line: "listen = {{ php_fpm_listen }}"
    - regexp: '^listen\.allowed_clients.?=.+$'
      line: "listen.allowed_clients = {{ php_fpm_listen_allowed_clients }}"
    - regexp: '^pm\.max_children.?=.+$'
      line: "pm.max_children = {{ php_fpm_pm_max_children }}"
    - regexp: '^pm\.start_servers.?=.+$'
      line: "pm.start_servers = {{ php_fpm_pm_start_servers }}"
    - regexp: '^pm\.min_spare_servers.?=.+$'
      line: "pm.min_spare_servers = {{ php_fpm_pm_min_spare_servers }}"
    - regexp: '^pm\.max_spare_servers.?=.+$'
      line: "pm.max_spare_servers = {{ php_fpm_pm_max_spare_servers }}"
  when: "'--enable-fpm' in php_source_configure_command"
  # notify: restart php-fpm